about:
  title: About
  link: /about
  hue: 70
  icon: ğŸ’¬
  sub: Who is this person?
# webStudio:
#   title: Web Studio
#   link: /web-studio
#   hue: 50
#   icon: ğŸ’»
#   sub: Hand crafted website for you
engineering:
  title: Engineering
  link: /engineering
  hue: 40
  icon: âš™ï¸
  sub: I join teams as web engineer
# ehp:
#   title: EHP Challenge
#   link: /ehp
#   hue: 10
#   icon: â¤ï¸â€ğŸ”¥
#   sub: 50 Emotional Healing Processes
portfolio:
  title: Portfolio
  link: /portfolio
  hue: 300
  icon: ğŸ¨
  sub: Showcase of my creations
writing:
  title: Writing
  link: /writing
  hue: 250
  icon: ğŸ“’
  sub: Notes, articles and blog